apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.components.nginx.base }}-deployment
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.nginx.deployment.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.nginx.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx.selectorLabels" . | nindent 8 }}
        {{- with .Values.nginx.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.nginx.container.name }}
        image: {{ .Values.nginx.container.image }}:{{ .Values.nginx.container.tag }}
        ports:
        - containerPort: {{ .Values.nginx.container.port }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: shared-storage
          mountPath: {{ .Values.nginx.container.staticFilesPath }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-{{ .Values.components.nginx.base }}-config
      - name: shared-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.components.nginx.base }}-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.components.nginx.base }}-service
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
  type: {{ .Values.nginx.service.type }}
  ports:
  - port: {{ .Values.nginx.service.port }}
    protocol: TCP
    targetPort: {{ .Values.nginx.container.port }}
    {{- if eq .Values.nginx.service.type "NodePort" }}
    nodePort: {{ .Values.nginx.service.nodePort }}
    {{- end }}