version: '3.8'
services:
  web:
    image: nouraldeen152/networkapp:${BUILD_NUMBER} 
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/app/djangoapp/staticfiles  # Mount staticfiles volume
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

  nginx:
    image: nouraldeen152/nginx_reverse_proxy:${BUILD_NUMBER} 
    ports:
      - "80:80"
    volumes:
      - staticfiles:/app/staticfiles  # Mount staticfiles volume 
    depends_on:
      - web

volumes:
  staticfiles: