# site.yml
- name: Apply selected roles
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'  # Accept new SSH keys automatically
    nginx_file_path: "{{ playbook_dir }}/../nginx/nginx.conf"  # Path to the external file


  roles:
    - { role: docker_install, when: "'docker_install' in selected_roles " } # 
    - { role: docker_compose, when: "'docker_compose' in selected_roles " } # 
    - { role: deploy_dockercommunity, when: "'deploy_dockercommunity' in selected_roles " } #     