# site.yml
- name: Apply selected roles
  hosts: all
  # become: yes
  # become_method: sudo
  roles:
    - { role: docker_install, when: "'docker_install' in selected_roles " } # 
    - { role: docker_compose, when: "'docker_compose' in selected_roles " } # 