apiVersion: v1
entries:
  networkapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-17T22:26:04.981941994+02:00"
    dependencies:
    - condition: ingress-nginx.enabled
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 4.7.1
    description: A Helm chart for Kubernetes
    digest: ac8688d534e4ef42bc478b2eefbd9ee09f687b2a6d8857624304ea53c526f0cb
    name: networkapp
    type: application
    urls:
    - https://nouraldeen417.github.io/DEPI_Graduation_Project_G5/charts/networkapp-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-17T22:26:04.96384804+02:00"
